version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: portal-meraki-backend:latest
    container_name: portal-meraki-backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/data:/app/data
    networks:
      - portal-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    image: portal-meraki-frontend:latest
    container_name: portal-meraki-frontend
    restart: unless-stopped
    ports:
      - "80:5173" # Servir la app en el puerto 80 del host
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - portal-network

networks:
  portal-network:
    driver: bridge
